### ISSUE TITLE
Minor suggestion 

### ISSUE THREAD

**Issue by sabberrahman** [Asfak00/zenui-library#9]
Mobile NavBar is not sufficient.adding Get started and Components here would be a good fix.

![Screenshot_20240701-124706.png](https://github.com/Asfak00/zenui-library/assets/140933637/a1da05f7-1889-429b-b6b8-e72c7c100322)

Also here we get 2 sideBar . Maybe merge and make it one . MOST efficient would be if you can make that 2nd Navbar the main mobileNav Bar 

![Screenshot_20240701-124739~2.png](https://github.com/Asfak00/zenui-library/assets/140933637/957255c0-2b26-4000-a105-c034340f71c2)

**Comment by Asfak00** [comment]
ZenUI is a platform designed to make it easy for beginners to get the components and templates they need. Everything in ZenUI is designed with beginners in mind so that anyone can use ZenUI with ease.

Get start and component buttons are provided in homepage itself so we have not given these in sidebar. And it is necessary to have two navbars so that anyone can easily recognize main navbar and component navbar.

Thanks for your comment. If necessary, we will consider the issues again!
